version: "2"

services:
  web:
    build: docker
    volumes:
       - ./html:/var/www/html
    links:
      - db
    environment:
      - VIRTUAL_HOST=mintpuur.local,www.mintpuur.local
      - DRUPAL_SETTINGS=development
    ports:
      - "80"
    container_name: mintpuur_web
    network_mode: "bridge"

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mintpuur_db
    ports:
      - "3302:3306"
    container_name: mintpuur_db
    volumes:
      - /var/lib/mysql
    network_mode: "bridge"

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.mintpuur.local
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"
    container_name: mintpuur_mailcatcher
